name = "ADAPT"
uuid = "cf1f529f-af3f-4d7a-b5f1-0e7d3fdd5852"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
BlockDavidson = "b4c031f8-e7c9-4879-896c-063a10ff8103"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PauliOperators = "be646426-f34c-4536-b1d4-a45a9633e6db"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
