name = "ADAPT"
uuid = "cf1f529f-af3f-4d7a-b5f1-0e7d3fdd5852"
authors = ["Kyle Sherbert <kyle.sherbert@vt.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
BlockDavidson = "b4c031f8-e7c9-4879-896c-063a10ff8103"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PauliOperators = "be646426-f34c-4536-b1d4-a45a9633e6db"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
